version: '3'
services:
  web:
    image: node:21.1.0
    container_name: my-express-app
    working_dir: /app/server
    volumes:
      - ./server:/app/server
    ports:
      - "3000:3000"
    command: npm start

  mongodb:
    image: mongo:latest
    container_name: kanban-board
    ports:
      - "27017:27017"